name: Get Filesystem

on: [push]
jobs:
  check-fs:
    runs-on: macos-latest
    steps:
      - name: free Macos Space
        run: |
          echo "$AGENT_TOOLSDIRECTORY"
          du -c -s -h /Users/runner/hostedtoolcache/*
          echo "Removing CodeQL"
          rm -rf $AGENT_TOOLSDIRECTORY/CodeQL
          rm -rf $AGENT_TOOLSDIRECTORY/Java_Temurin-Hotspot_jdk
          ls -la /Users/runner/hostedtoolcache
          du -c -s -h /Users/runner/hostedtoolcache