name: Get Filesystem

on: [push]
jobs:
  check-fs:
    runs-on: macos-latest
    steps:
      - name: free Macos Space
        run: |
          echo "$AGENT_TOOLSDIRECTORY"
          du -c -s -h /Users/runner/hostedtoolcache
          echo "Removing CodeQL"
          rm -rf $AGENT_TOOLSDIRECTORY/hostedtoolcache/CodeQL
          rm -rf /Users/runner/hostedtoolcache/*
          ls -la /Users/runner/hostedtoolcache/CodeQL
          du -c -s -h /Users/runner/hostedtoolcache