name: Get Filesystem

on: [push]
jobs:
  check-fs:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: free Macos Space
        run: |
          echo "$AGENT_TOOLSDIRECTORY"
          ls -la /Users/runner