name: Get Filesystem

on: [push]
jobs:
  check-fs:
    runs-on: macos-latest
    steps:
      - name: free Macos Space
        run: |
          echo "$AGENT_TOOLSDIRECTORY"
          rm -rf $AGENT_TOOLSDIRECTORY/hostedtoolcache/CodeQL
          ls -la /Users/runner/hostedtoolcache
          du -c -s -h /Users/runner/hostedtoolcache/*
          ls -la /Users/runner
          ls -la /Users/runner/.android
          du -c -s -h /Users/runner/.android
          ls -la /Users/runner/.net
          du -c -s -h /Users/runner/utils
          ls -la /Users/runner/utils
          du -c -s -h /Users/runner/*