name: Get Filesystem

on: [push]
jobs:
  check-fs:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: free Macos Space
        run: |
          echo "$AGENT_TOOLSDIRECTORY"
          ls -la /Users/runner
          ls -la /Users/runner/.android
          du -c -s -h /Users/runner/.android
          ls -la /Users/runner/.net
          du -c -s -h /Users/runner/.net